apiVersion: v1
kind: Service
metadata:
    name: example-cb 
    labels:
        app: example-cb 
spec:
    ports:
        - name: http
          port: 3000
          targetPort: 3000
          protocol: TCP
          nodePort: 30039
    type: NodePort
    selector:
        app: loadgen 
